Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "test/**/*"
    - "lib/google/idtoken/verifier/cli/**/*"

Style/FileName:
  Exclude:
    - 'lib/google-idtoken-verifier.rb'
