language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.8
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.3.0
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
  fast_finish: true
before_install: gem install bundler -v 1.11.2
